# Autogenerated by nbdev

d = { 'settings': { 'branch': 'Main',
                'doc_baseurl': '/tinyai',
                'doc_host': 'https://GalaxUniv.github.io',
                'git_url': 'https://github.com/GalaxUniv/tinyai',
                'lib_path': 'tinyai'},
  'syms': { 'tinyai.core': {'tinyai.core.foo': ('core.html#foo', 'tinyai/core.py')},
            'tinyai.training': { 'tinyai.training.Dataset': ('minibatch_training.html#dataset', 'tinyai/training.py'),
                                 'tinyai.training.Dataset.__getitem__': ( 'minibatch_training.html#dataset.__getitem__',
                                                                          'tinyai/training.py'),
                                 'tinyai.training.Dataset.__init__': ('minibatch_training.html#dataset.__init__', 'tinyai/training.py'),
                                 'tinyai.training.Dataset.__len__': ('minibatch_training.html#dataset.__len__', 'tinyai/training.py'),
                                 'tinyai.training.accuracy': ('minibatch_training.html#accuracy', 'tinyai/training.py'),
                                 'tinyai.training.fit': ('minibatch_training.html#fit', 'tinyai/training.py'),
                                 'tinyai.training.get_dls': ('minibatch_training.html#get_dls', 'tinyai/training.py'),
                                 'tinyai.training.report': ('minibatch_training.html#report', 'tinyai/training.py')}}}
